version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "3002:3002"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/db:/app/db
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - appnet

networks:
  appnet:
