
### 
GET http://localhost:3002/api/cursos/disponibles

###
GET http://localhost:3002/api/directivos/dir-001

###
GET http://localhost:3002/api/docentes/materias


###
GET http://localhost:3002/api/estadisticas/cursos/1A-SEC

###
GET http://localhost:3002/api/alumnos/estudiante/51000000/inasistencias